services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: emaildb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d emaildb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M

  greenmail:
    image: greenmail/standalone:2.1.0
    container_name: greenmail
    ports:
      - "3025:3025" # SMTP
      - "3143:3143" # IMAP
      - "8081:8080"
    environment:
      - JAVA_OPTS=-Dgreenmail.verbose -Dgreenmail.users=user:pass@localhost
    deploy:
      resources:
        limits:
          memory: 256M

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - POSTGRES_HOST=postgres
      - UPLOAD_DIR=/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 256M

  spark-streaming:
    build: ./spark
    container_name: spark-streaming
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./spark:/opt/bitnami/spark/scripts
      - ./models:/opt/bitnami/spark/models
    command: >
      spark-submit 
      --packages org.postgresql:postgresql:42.7.2 
      /opt/bitnami/spark/scripts/streaming_classifier.py
    deploy:
      resources:
        limits:
          memory: 1800M

  spark-batch:
    build: ./spark
    container_name: spark-batch
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./spark:/opt/bitnami/spark/scripts
      - ./models:/opt/bitnami/spark/models
      - ./uploads:/opt/bitnami/spark/uploads
      - ./spark/checkpoints:/tmp/spark_checkpoint_uploads
    command: >
      spark-submit 
      --packages org.postgresql:postgresql:42.7.2 
      /opt/bitnami/spark/scripts/batch_processor.py
    deploy:
      resources:
        limits:
          memory: 2048M

volumes:
  postgres_data: